package MainTests;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.io.FileHandler;
import testBase.TestBase;

import java.io.File;
import java.io.IOException;
import java.util.Map;

public class PositionRefBottom extends TestBase {
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void openBaseUrl() {
        getDriver().get(getBASE_URL());
    }

    @Test
    public void PositionRefBottomTest() {
        WebElement Fast50 = getDriver().findElement(By.cssSelector("#award-14"));
        Fast50.click();
        Assert.assertEquals(true, Fast50.isDisplayed());
        System.out.println(Fast50.getAccessibleName());

        WebElement ItProduct = getDriver().findElement(By.cssSelector("#award-12"));
        ItProduct.click();
        Assert.assertEquals(true, ItProduct.isDisplayed());
        System.out.println(ItProduct.getAccessibleName());

        WebElement BestSupport = getDriver().findElement(By.cssSelector("#award-30"));
        BestSupport.click();
        Assert.assertEquals(true, BestSupport.isDisplayed());
        System.out.println(BestSupport.getAccessibleName());

//        WebElement HighPerformer = getDriver().findElement(By.cssSelector("#award-29"));
//        HighPerformer.click();
//        Assert.assertEquals(true, HighPerformer.isDisplayed());
//        System.out.println(HighPerformer.getAccessibleName());

        WebElement G2momtul = getDriver().findElement(By.cssSelector("#award-26"));
        G2momtul.click();
        Assert.assertEquals(true, G2momtul.isDisplayed());
        System.out.println(G2momtul.getAccessibleName());

        WebElement EasiestToDo = getDriver().findElement(By.cssSelector("#award-27"));
        EasiestToDo.click();
        Assert.assertEquals(true, EasiestToDo.isDisplayed());
        System.out.println(EasiestToDo.getAccessibleName());

        WebElement ItProduct2 = getDriver().findElement(By.cssSelector("#award-10"));
        ItProduct2.click();
        Assert.assertEquals(true, ItProduct2.isDisplayed());
        System.out.println(ItProduct2.getAccessibleName());

        WebElement Deloite = getDriver().findElement(By.cssSelector("#award-11"));
        Deloite.click();
        Assert.assertEquals(true, Deloite.isDisplayed());
        System.out.println(Deloite.getAccessibleName());

    }
    @After
    public void tearDown() throws IOException {
        getDriver().getWindowHandles();
        TakesScreenshot screenShot =(TakesScreenshot)getDriver();
        FileHandler.copy(screenShot.getScreenshotAs(OutputType.FILE), new File("screenshot.png"));
        System.out.println(getDriver().getCurrentUrl());


    }
}
