package navbarsTests;// Generated by Selenium IDE

import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import testBase.TestBase;

import java.util.Map;
public class Login extends TestBase {
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void openBaseUrl() {
        getDriver().get(getBASE_URL());
    }

    @Test
    public void topBarTest() {
        getDriver().get("https://denevy.eu/");
        getDriver().findElement(By.xpath("//*[@id=\"app\"]/div[1]/div/div/div[2]/div[2]/a/i")).click();
        getDriver().findElement(By.id("email")).click();
        getDriver().findElement(By.id("email")).sendKeys("vaclaviklubomir@gmail.com");
        getDriver().findElement(By.cssSelector(".card-body > form")).click();
        getDriver().findElement(By.id("password")).click();
        getDriver().findElement(By.id("password")).sendKeys("123456");
        getDriver().findElement(By.id("remember")).click();
        getDriver().findElement(By.cssSelector(".btn")).click();
        getDriver().findElement(By.cssSelector("strong")).click();
        //overenie hesla
        //Assert.assertEquals(getDriver().findElement(By.xpath(/html/body/div/main/div/div/div/div/div/div[2]/form/div[1]/div/span/strong)));
    }
}