package navbarsTests;// Generated by Selenium IDE

import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebElement;
import testBase.TestBase;

import java.util.Map;
public class Login extends TestBase {
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void openBaseUrl() {
        getDriver().get(getBASE_URL() + "/login");
    }

    @Test
    public void topBarTest() {
        WebElement name = getDriver().findElement(By.id("email"));
        name.click();
        //name.sendKeys("vaclaviklubomir@gmail.com");
        Assert.assertNotNull(name.getText());
        Assert.assertNotNull(name);
        System.out.println("login name is correct");

        getDriver().findElement(By.id("password")).sendKeys("123456");
        getDriver().findElement(By.id("remember")).click();
        getDriver().findElement(By.cssSelector(".btn")).click();

        WebElement login = getDriver().findElement(By.cssSelector(".btn"));
        Assert.assertEquals(true, login.isEnabled());
        System.out.println("login is working");

    }
}