package navbarsTests;// Generated by Selenium IDE

import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import testBase.TestBase;

import java.util.Map;
public class TopBar extends TestBase {
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void openBaseUrl() {
    getDriver().get(getBASE_URL());
  }

  @Test
  public void topBarTest() {
    getDriver().findElement(By.linkText("+420 774 494 633")).click();
    getDriver().findElement(By.linkText("sales@denevy.eu")).click();
    getDriver().findElement(By.cssSelector("span:nth-child(3) .fa-facebook-f")).click();
    getDriver().findElement(By.cssSelector("span:nth-child(3) .fa-instagram")).click();
    getDriver().findElement(By.cssSelector("span:nth-child(3) .fa-twitter")).click();
    getDriver().findElement(By.cssSelector("span:nth-child(3) .fa-linkedin-in")).click();
    getDriver().findElement(By.linkText("Marketplace")).click();
    getDriver().findElement(By.linkText("Blog")).click();
    getDriver().findElement(By.cssSelector(".col-12 > .float-right .fas")).click();
    getDriver().findElement(By.id("lang")).click();
    getDriver().findElement(By.cssSelector(".show .dropdown-item")).click();
  }
}
