package navbarsTests;// Generated by Selenium IDE

import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebElement;
import testBase.TestBase;

import javax.swing.*;
import java.io.File;
import java.util.Map;

public class TopBar extends TestBase {
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void openBaseUrl() {
    getDriver().get(getBASE_URL());
  }

  @Test
  public void topBarTest() {
    WebElement phone = getDriver().findElement(By.linkText("+420 774 494 633"));
    phone.click();
    Assert.assertEquals(true, phone.isEnabled());
    System.out.println(phone.getText());

    WebElement email = getDriver().findElement(By.linkText("sales@denevy.eu"));
    email.click();
    Assert.assertEquals(true, email.isEnabled());
    System.out.println(email.getText());

    WebElement fbIcon = getDriver().findElement(By.cssSelector("span:nth-child(3) .fa-facebook-f"));
    fbIcon.click();
    Assert.assertEquals(true, fbIcon.isEnabled());
    Assert.assertEquals(true, fbIcon.isDisplayed());
    System.out.println(fbIcon);

    WebElement ig = getDriver().findElement(By.cssSelector("span:nth-child(3) .fa-instagram"));
    ig.click();
    Assert.assertEquals(true, ig.isEnabled());
    Assert.assertEquals(true, ig.isDisplayed());

  }
}
/*
    //list of waiting items to test
    getDriver().findElement(By.cssSelector("span:nth-child(3) .fa-linkedin-in"))
    getDriver().findElement(By.linkText("Marketplace"))
    getDriver().findElement(By.linkText("Blog"))
    getDriver().findElement(By.cssSelector(".col-12 > .float-right .fas"))
    getDriver().findElement(By.id("lang"))
    getDriver().findElement(By.cssSelector(".show .dropdown-item"))*/



